MVC5-StokTakip/MVC5-StokTakip/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5_StokTakip.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MVC5_StokTakip.Controllers
{
	public class KategoriController : Controller
	{
		DBStokTakipEntities db = new DBStokTakipEntities();
		// GET: Kategori
		public ActionResult Index(int page=1)
		{
			//var readitem = db.TBLKATEGORILER.ToList();
			var readitem = db.TBLKATEGORILER.ToList().ToPagedList(page,5);

			return View(readitem);
		}

		public ActionResult Delete(int id)
		{
			var deleteitem = db.TBLKATEGORILER.Find(id);
			db.TBLKATEGORILER.Remove(deleteitem);
			db.SaveChanges();
			return RedirectToAction("Index");
		}


		public ActionResult Update(int id)
		{
			var updateitemm = db.TBLKATEGORILER.Find(id);

			return View("Update", updateitemm);
		}

		public ActionResult UpdateMethod(TBLKATEGORILER item)
		{
			var updateitem = db.TBLKATEGORILER.Find(item.KATEGORIID);
			updateitem.KATEGORIAD = item.KATEGORIAD;
			db.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Ekle()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Ekle(TBLKATEGORILER insertitem)
		{
			if(!ModelState.IsValid)
			{
				return View("Ekle");
			}
			db.TBLKATEGORILER.Add(insertitem);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

MVC5-StokTakip/MVC5-StokTakip/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5_StokTakip.Models.Entity;

namespace MVC5_StokTakip.Controllers
{
    public class MusteriController : Controller
    {
		DBStokTakipEntities db = new DBStokTakipEntities();

        // GET: Musteri
        public ActionResult Index(string searchitem)
        {
			var selectitem = from item in db.TBLMUSTERILER select item;
			if(!string.IsNullOrEmpty(searchitem))
			{
				selectitem = selectitem.Where(m => m.MUSTERIAD.Contains(searchitem));
			}

			return View(selectitem.ToList());
        }

		public ActionResult Delete(int id)
		{
			var deleteitem = db.TBLMUSTERILER.Find(id);
			db.TBLMUSTERILER.Remove(deleteitem);
			db.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Ekle()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Ekle(TBLMUSTERILER item)
		{
			if(!ModelState.IsValid)
			{
				return View("Ekle");
			}
			db.TBLMUSTERILER.Add(item);
			db.SaveChanges();

			return RedirectToAction("Index");
		}

		public ActionResult Update(int id)
		{
			var updateitemm = db.TBLMUSTERILER.Find(id);

			return View("Update",updateitemm);
		}

		public ActionResult UpdateMethod(TBLMUSTERILER item)
		{
			var updateitem = db.TBLMUSTERILER.Find(item.MUSTERIID);
			updateitem.MUSTERIAD = item.MUSTERIAD;
			updateitem.MUSTERISOYAD = item.MUSTERISOYAD;
			db.SaveChanges();

			return RedirectToAction("Index");
		}

		//public ActionResult UpdateMethod(TBLMUSTERILER p1)
		//{
		//	var musteri = db.TBLMUSTERILER.Find(p1.MUSTERIID);
		//	musteri.MUSTERIAD = p1.MUSTERIAD;
		//	musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
		//	db.SaveChanges();

		//	return RedirectToAction("Index");
		//}
    }
}

MVC5-StokTakip/MVC5-StokTakip/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5_StokTakip.Models.Entity;

//using PagedList;
//using PagedList.Mvc;

namespace MVC5_StokTakip.Controllers
{
    public class SatisController : Controller
    {
		DBStokTakipEntities db = new DBStokTakipEntities();

        // GET: Satis
        public ActionResult Index()
        {
			return View();
        }
		
		/*	Pageing işlemi için oluşturulan ActionResult
		public ActionResult Index(int page = 1)
		{
			var readitem = db.TBLSATISLAR.ToList().ToPagedList(page, 5);
			return View(readitem);
		}
		*/
		[HttpPost]
		public ActionResult Sales(TBLSATISLAR saleitem)
		{
			db.TBLSATISLAR.Add(saleitem);
			db.SaveChanges();

			return View("Index");
		}
    }
}

MVC5-StokTakip/MVC5-StokTakip/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5_StokTakip.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MVC5_StokTakip.Controllers
{
    public class UrunController : Controller
    {
		DBStokTakipEntities db = new DBStokTakipEntities();

        // GET: Urun
        public ActionResult Index(int page=1)
        {
			var readitem = db.TBLURUNLER.ToList().ToPagedList(page, 5);
			return View(readitem);
        }

		[HttpGet]
		public ActionResult Ekle()
		{

			List<SelectListItem> item = (from tableitem in db.TBLKATEGORILER.ToList()
										 select new SelectListItem
										 {
											 Text = tableitem.KATEGORIAD,
											 Value = tableitem.KATEGORIID.ToString()
										 }).ToList();
			ViewBag.dgr = item;
			return View();
		}

		[HttpPost]
		public ActionResult Ekle(TBLURUNLER item)
		{
			var insertitem = db.TBLKATEGORILER.Where(m => m.KATEGORIID == item.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
			item.TBLKATEGORILER = insertitem;

			if (!ModelState.IsValid)
			{
				return View(item);
			}
			
			db.TBLURUNLER.Add(item);
			db.SaveChanges();

			return RedirectToAction("Index");
		}

		public ActionResult Delete(int id)
		{
			var deleteitem = db.TBLURUNLER.Find(id);
			db.TBLURUNLER.Remove(deleteitem);
			db.SaveChanges();

			return RedirectToAction("Index");
		}

		public ActionResult Update(int id)
		{
			var updateitemm = db.TBLURUNLER.Find(id);
			List<SelectListItem> item = (from tableitem in db.TBLKATEGORILER.ToList()
										 select new SelectListItem
										 {
											 Text = tableitem.KATEGORIAD,
											 Value = tableitem.KATEGORIID.ToString()
										 }).ToList();
			ViewBag.dgr = item;
			return View("Update",updateitemm);
		}

		public ActionResult UpdateMethod(TBLURUNLER item)
		{
			var updateitem = db.TBLURUNLER.Find(item.URUNID);
			updateitem.URUNAD = item.URUNAD;
			updateitem.URUNMARKA = item.URUNMARKA;

			//updateitem.URUNKATEGORI = item.URUNKATEGORI;
			var kategori = db.TBLKATEGORILER.Where(m => m.KATEGORIID == item.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
			updateitem.URUNKATEGORI= kategori.KATEGORIID;

			updateitem.URUNFIYAT = item.URUNFIYAT;
			updateitem.URUNSTOKADET = item.URUNSTOKADET;
			db.SaveChanges();

			return RedirectToAction("Index");
		}

	}
}

MVC5-StokTakip/MVC5-StokTakip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stok Takip Uygulaması v0.1</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Stok Takip Uygulaması", "Index", "Urun", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse col-md-7">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kategoriler", "Index", "Kategori")</li>
                    <li>@Html.ActionLink("Ürünler", "Index", "Urun")</li>
                    <li>@Html.ActionLink("Müşteriler", "Index", "Musteri")</li>
                    <li>@Html.ActionLink("Satışlar", "Index", "Satis")</li>
                </ul>
            </div>
            <div class="justify-content-end">
                <ul class="nav navbar-nav justify-content-end">
                    <li><a href="#">Yardım</a></li>
                    <li><a href="#">İletişim</a></li>
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p><b>&copy;</b>@DateTime.Now.Year - <b>Stok Takip Uygulaması</b> v0.1</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>